name: hello world
on:
  push:
      branches:
           - main
  pull_request:
      branches:
           - main
jobs:
   hello:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: hello world
         run: echo "hello world"
         shell: bash
   good_bye:
      runs-on: ubuntu-latest
      steps:
       -  name: goodbye_world
          run: echo "goodbye world"
          shell: bash
   step3:
       runs-on: ubuntu-latest
       steps:
         - name: hi
           run: echo "hi"
           shell: bash
   step4:
        runs-on: ubuntu-latest
        steps: 
           - name: caze-lab
             run: echo "this is caze-lab"
             shell: bash
