name: create comment on newly created issue
on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    permissions: # Ensure proper permissions are set
      issues: write

    steps:
      - name: "Dump the GitHub event"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - this is a GitHub workflow
            - Created by nivedita
            
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-api:
      runs-on: ubuntu-latest
      steps:
        - name: create comment with api
          run: |
              gh api -X POST \
                 https://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER/comments \
                 -f body='
                        comment from api call
                        '
          env:
             GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
             ORGANIZATION: ${{ github.event.organisation.login }}
             REPOSITORY: ${{ github.event.repository.name }}
             ISSUE_NUMBER: ${{ github.event.issue.number }}
        
