name: create comment on newly created issue
on:
  issues:
     types: [opened]
jobs:
  comment-with-action:
     runs-on: ubuntu-latest
     steps:
       - name: "dump github"
         run: echo '${{ toJSON(github.event) }}' | jq
         shell: bash
